#app
server:
  port: 8080
#  context-path: /

#spring
spring:
  devtools:
    restart:
      enabled: false
  profiles:
    active: ${build.profile.id}

  # H2 DATABASE CONFIG
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    schema: classpath:/db/schema-h2.sql
    data: classpath:/db/data-h2.sql
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
    platform: h2
    initialization-mode: always
    continue-on-error: true
  h2:
    console:
      enabled: true
      path: /console
  kafka:
    producer:
      bootstrap-servers: 192.168.1.252:9092

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.auto.entity
  typeEnumsPackage: com.auto.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: h2
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
##logging
#logging:
#  level: warn
logging:
  config: classpath:logback-spring.xml
#  level: warn

solr:
  #  url: http://admin:nanquan2017@47.98.187.132:7001/solr
  url: http://0.0.0.0:8983/solr



# cache BeanName
#specify.cache.service=memCacheService
#specify.cache.service=redisCacheService
specify:
  cache:
    service: ehCacheService

# confirmOrderCacheName
confirm:
  order:
    cache:
      name: confirmOrderCache

# redis config
jedis:
  pool:
    host: 192.168.1.252
    port: 6379
    config:
      maxTotal: 60
      maxIdle: 10
      maxWaitMillis: 30000
      password: nq123456
      database: 0
      timeout: 10000

      # key expire time,timeunit: milliseconds , default value: 300s
      expire:
        timeout: 300000